In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

e:\ANN CLASSIFICATION PROJECT\venv\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [16]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [17]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 100374.3047 - mae: 100374.3047 - val_loss: 98508.3125 - val_mae: 98508.3125
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 99611.4609 - mae: 99611.4609 - val_loss: 96963.6641 - val_mae: 96963.6641
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 96908.0391 - mae: 96908.0391 - val_loss: 92967.6797 - val_mae: 92967.6797
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 91476.2188 - mae: 91476.2188 - val_loss: 86137.0078 - val_mae: 86137.0078
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 83454.2422 - mae: 83454.2422 - val_loss: 77288.7344 - val_mae: 77288.7344
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 74094.4219 - mae: 74094.4219 - val_loss: 68236.2266 - val_mae: 68236.2266
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 65169.2852 - mae: 65169.2852 - val_loss: 60633.4023 - val_mae: 60633.4023
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 58219.6094 - mae: 58219.6094 - val_loss: 55272.3711 - val_mae: 55272.3711
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 53890.9102 - mae: 53890.9102 - val_loss: 52456.5898 - val_mae: 52456.5898
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 51741.5898 - mae: 51741.5898 - val_loss: 51330.2148 - val_mae: 51330.2148
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 50864.0703 - mae: 50864.0703 - val_loss: 50962.4531 - val_mae: 50962.4531
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50543.0391 - mae: 50543.0391 - val_loss: 50844.1484 - val_mae: 50844.1484
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50393.5781 - mae: 50393.5781 - val_loss: 50758.6953 - val_mae: 50758.6953
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 50308.5547 - mae: 50308.5547 - val_loss: 50712.2383 - val_mae: 50712.2383
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50234.4609 - mae: 50234.4609 - val_loss: 50675.4609 - val_mae: 50675.4609
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50175.1133 - mae: 50175.1133 - val_loss: 50638.1328 - val_mae: 50638.1328
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50122.9023 - mae: 50122.9023 - val_loss: 50594.0117 - val_mae: 50594.0117
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50074.3594 - mae: 50074.3594 - val_loss: 50556.4219 - val_mae: 50556.4219
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50036.6562 - mae: 50036.6562 - val_loss: 50528.2656 - val_mae: 50528.2656
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49996.7812 - mae: 49996.7812 - val_loss: 50498.5703 - val_mae: 50498.5703
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49964.3086 - mae: 49964.3086 - val_loss: 50466.9688 - val_mae: 50466.9688
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49936.0469 - mae: 49936.0469 - val_loss: 50446.1680 - val_mae: 50446.1680
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49906.0391 - mae: 49906.0391 - val_loss: 50429.9922 - val_mae: 50429.9922
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49879.4570 - mae: 49879.4570 - val_loss: 50411.5938 - val_mae: 50411.5938
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49853.7656 - mae: 49853.7656 - val_loss: 50395.2578 - val_mae: 50395.2578
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49832.4023 - mae: 49832.4023 - val_loss: 50383.0664 - val_mae: 50383.0664
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49812.3789 - mae: 49812.3789 - val_loss: 50375.4883 - val_mae: 50375.4883
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49793.1758 - mae: 49793.1758 - val_loss: 50372.5664 - val_mae: 50372.5664
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49778.2578 - mae: 49778.2578 - val_loss: 50355.0547 - val_mae: 50355.0547
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49754.1133 - mae: 49754.1133 - val_loss: 50349.0703 - val_mae: 50349.0703
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49737.2422 - mae: 49737.2422 - val_loss: 50348.3047 - val_mae: 50348.3047
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49721.5859 - mae: 49721.5859 - val_loss: 50340.0117 - val_mae: 50340.0117
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49706.3008 - mae: 49706.3008 - val_loss: 50333.9141 - val_mae: 50333.9141
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49690.0742 - mae: 49690.0742 - val_loss: 50324.0234 - val_mae: 50324.0234
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49674.8047 - mae: 49674.8047 - val_loss: 50327.5156 - val_mae: 50327.5156
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49660.4766 - mae: 49660.4766 - val_loss: 50325.0391 - val_mae: 50325.0391
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49646.2656 - mae: 49646.2656 - val_loss: 50315.4961 - val_mae: 50315.4961
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49634.3203 - mae: 49634.3203 - val_loss: 50313.8867 - val_mae: 50313.8867
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49624.6367 - mae: 49624.6367 - val_loss: 50311.6953 - val_mae: 50311.6953
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49612.2188 - mae: 49612.2188 - val_loss: 50313.7617 - val_mae: 50313.7617
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49599.3008 - mae: 49599.3008 - val_loss: 50301.7305 - val_mae: 50301.7305
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49591.8359 - mae: 49591.8359 - val_loss: 50307.8281 - val_mae: 50307.8281
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49579.4961 - mae: 49579.4961 - val_loss: 50300.9258 - val_mae: 50300.9258
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49572.4922 - mae: 49572.4922 - val_loss: 50299.5273 - val_mae: 50299.5273
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49561.5352 - mae: 49561.5352 - val_loss: 50287.4766 - val_mae: 50287.4766
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49554.7070 - mae: 49554.7070 - val_loss: 50290.6055 - val_mae: 50290.6055
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49544.2461 - mae: 49544.2461 - val_loss: 50288.1211 - val_mae: 50288.1211
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49535.9648 - mae: 49535.9648 - val_loss: 50288.3320 - val_mae: 50288.3320
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49531.7070 - mae: 49531.7070 - val_loss: 50280.4258 - val_mae: 50280.4258
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49522.2734 - mae: 49522.2734 - val_loss: 50281.1914 - val_mae: 50281.1914
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49514.7305 - mae: 49514.7305 - val_loss: 50285.5352 - val_mae: 50285.5352
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49509.7344 - mae: 49509.7344 - val_loss: 50282.0469 - val_mae: 50282.0469
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49501.0039 - mae: 49501.0039 - val_loss: 50281.2383 - val_mae: 50281.2383
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49492.9844 - mae: 49492.9844 - val_loss: 50269.8906 - val_mae: 50269.8906
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49487.6328 - mae: 49487.6328 - val_loss: 50275.2695 - val_mae: 50275.2695
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49477.8555 - mae: 49477.8555 - val_loss: 50272.8281 - val_mae: 50272.8281
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49471.9102 - mae: 49471.9102 - val_loss: 50269.7656 - val_mae: 50269.7656
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49461.0625 - mae: 49461.0625 - val_loss: 50295.1914 - val_mae: 50295.1914
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49468.3438 - mae: 49468.3438 - val_loss: 50283.5938 - val_mae: 50283.5938
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49451.8047 - mae: 49451.8047 - val_loss: 50274.0273 - val_mae: 50274.0273
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49447.1445 - mae: 49447.1445 - val_loss: 50276.0625 - val_mae: 50276.0625
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49441.5312 - mae: 49441.5312 - val_loss: 50271.2852 - val_mae: 50271.2852
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49435.7070 - mae: 49435.7070 - val_loss: 50268.3828 - val_mae: 50268.3828
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49430.1914 - mae: 49430.1914 - val_loss: 50272.3750 - val_mae: 50272.3750
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49426.5312 - mae: 49426.5312 - val_loss: 50268.4883 - val_mae: 50268.4883
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49419.4609 - mae: 49419.4609 - val_loss: 50266.9297 - val_mae: 50266.9297
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49416.9414 - mae: 49416.9414 - val_loss: 50273.5703 - val_mae: 50273.5703
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49410.6250 - mae: 49410.6250 - val_loss: 50272.5742 - val_mae: 50272.5742
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49404.9688 - mae: 49404.9688 - val_loss: 50267.8008 - val_mae: 50267.8008
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49402.6211 - mae: 49402.6211 - val_loss: 50262.8672 - val_mae: 50262.8672
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49399.3711 - mae: 49399.3711 - val_loss: 50271.9648 - val_mae: 50271.9648
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49392.7891 - mae: 49392.7891 - val_loss: 50271.1406 - val_mae: 50271.1406
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49389.4023 - mae: 49389.4023 - val_loss: 50285.8438 - val_mae: 50285.8438
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49383.6406 - mae: 49383.6406 - val_loss: 50278.7031 - val_mae: 50278.7031
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49381.7344 - mae: 49381.7344 - val_loss: 50290.3594 - val_mae: 50290.3594
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49379.1094 - mae: 49379.1094 - val_loss: 50287.1211 - val_mae: 50287.1211
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49374.1953 - mae: 49374.1953 - val_loss: 50276.0742 - val_mae: 50276.0742
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49368.9766 - mae: 49368.9766 - val_loss: 50279.5781 - val_mae: 50279.5781
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49365.7656 - mae: 49365.7656 - val_loss: 50276.7539 - val_mae: 50276.7539
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49359.9141 - mae: 49359.9141 - val_loss: 50289.1758 - val_mae: 50289.1758

In [18]:
%load_ext tensorboard

In [22]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 8464), started 0:01:05 ago. (Use '!kill 8464' to kill it.)

In [20]:
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50262.8672 - mae: 50262.8672
Test MAE : 50262.8671875

In [21]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.